CREATE TABLE IF NOT EXISTS curvy_dolphin.comments
(
    id         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    video_id   UUID NOT NULL,
    user_id    BIGINT NOT NULL,
    text       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT comments_pkey
    PRIMARY KEY (id),

    CONSTRAINT fk_comments_video
    FOREIGN KEY (video_id)
    REFERENCES curvy_dolphin.videos (id)
    ON DELETE CASCADE,

    CONSTRAINT fk_comments_user
    FOREIGN KEY (user_id)
    REFERENCES curvy_dolphin.users (user_id)
    ON DELETE CASCADE
    );

CREATE INDEX idx_comments_video_id
    ON curvy_dolphin.comments (video_id);

CREATE INDEX idx_comments_user_id
    ON curvy_dolphin.comments (user_id);

CREATE INDEX idx_comments_created_at
    ON curvy_dolphin.comments (created_at DESC);