CREATE TABLE IF NOT EXISTS curvy_dolphin.video_shares
(
    id         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    video_id   UUID NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT video_shares_pkey
    PRIMARY KEY (id),

    CONSTRAINT fk_video_shares_video
    FOREIGN KEY (video_id)
    REFERENCES curvy_dolphin.videos (id)
    ON DELETE CASCADE,

    CONSTRAINT fk_video_shares_user
    FOREIGN KEY (user_id)
    REFERENCES curvy_dolphin.users (user_id)
    ON DELETE CASCADE
    );

CREATE INDEX idx_video_shares_video_id
    ON curvy_dolphin.video_shares (video_id);

CREATE INDEX idx_video_shares_user_id
    ON curvy_dolphin.video_shares (user_id);

CREATE INDEX idx_video_shares_created_at
    ON curvy_dolphin.video_shares (created_at DESC);