-- Table: curvy_dolphin.users

-- DROP TABLE IF EXISTS curvy_dolphin.users;

CREATE TABLE IF NOT EXISTS curvy_dolphin.users
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying(255) COLLATE pg_catalog."default",
    provider_id character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    avatar_url character varying(255) COLLATE pg_catalog."default",
    created_at timestamp,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_provider_id_unique UNIQUE (provider_id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS curvy_dolphin.users
    OWNER to postgres;